### ISSUE TITLE
Add poster support

### ISSUE THREAD

**Issue by MarkJaroski** [jakopako/croncert-config#150]
Lots of venues continue to use posters for publicity, and also provide them on their websites. It would be nice to be able to include them in the data, even if not all publishing sides want to risk using posters.

**Comment by jakopako** [comment]
Do you mean pdf files? Or other file formats? 

Could you give an example of such a website?

**Comment by MarkJaroski** [comment]
I guess let's start with the Rocking Chair, but they pretty much all have imaeges.

Croncert.ch doesn't display images, and that's fine, but other implementations someday might decide to use them. I understand that there might be copyright issues, so feel free to say no.

**Comment by jakopako** [comment]
Ah ok I understand now. I think for croncert we won't include posters for now. This makes a bunch of things easier, such as the copyright issues you mentioned but also storage. Also goskyr doesn't yet support scraping images so there might be our starting point should we want to support this 😅 
So I'm closing this for now. But thanks for your input :)
