### ISSUE TITLE
Amalgame failed to be pushed to the api

### ISSUE THREAD

**Issue by jakopako** [jakopako/croncert-config#363]
Error:

error while adding new events. Status Code: 400 Response: {"error":"Key: 'Event.ImageURL' Error:Field validation for 'ImageURL' failed on the 'url' tag","message":"failed to validate event {Title:VOX LOW + GREY LIPS + TOMORROW’S GHOST Location:L’Amalgame City:Yverdon-les-Bains Country:Switzerland Date:2024-02-16 20:00:00 +0100 +0100 Offset:0 URL:https://www.amalgameclub.ch/programme/vox-low-grey-lips/ ImageURL:https://www.amalgameclub.ch/wp-content/uploads/2023/11/2023_19_09_VOX_LOW_144MARION_BARAT-1.jpg Comment: Type:concert SourceURL:https://www.amalgameclub.ch/programme/ Geolocation:[] MongoGeolocation:{GeoJSONType: Coordinates:[]}}","succes":false}

Check what's wrong with the image url.

**Comment by jakopako** [comment]
@MarkJaroski unfortunately I had to remove the imageUrl field temporarily because the above error prevents a big batch of concerts from being written to the api. I'll investigate why this happens. Didn't immediately see the problem. Moreover, now I have an incentive to improve the api batch processing 😅

**Comment by MarkJaroski** [comment]
Weird. It's HTML encoded so I don't get why it should cause an issue, but OK.

**Comment by jakopako** [comment]
Probably more of an issue/bug in goskyr or the api not the website.

**Comment by jakopako** [comment]
The problem seems to have been only one single image url.. I readded the field and will update the api to not reject entire batches because of one failed event validation.

**Comment by jakopako** [comment]
https://github.com/jakopako/event-api/commit/a96ea741f088c7559a59d668dd35eca9ce8d3bf6 event api improvement.

**Comment by MarkJaroski** [comment]
I'll do some testing this morning.
